services:
  - type: web
    name: onlyfab
    runtime: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
